name: Ejecutar Hola Mundo con Pruebas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        working-directory: /home/runner/work/Prueba
        run: npm install

      - name: Ejecutar pruebas con Jest
        working-directory: /home/runner/work/Prueba
        run: npm test

      - name: Ejecutar script Hola Mundo
        working-directory: /home/runner/work/Prueba
        run: node index.js